### ISSUE TITLE
Great Mod!

### ISSUE THREAD

**Issue by RHuehne** [IWhoI/SubnauticaVREnhancements#10]
Hi There,

More a question than an issue:

Maybe I missed it but is there any option to allow that the mouse control does not only left and right, but also up and down?
I am just up to start the game, and would like to use mouse / keyboard / vr.  Currently to get up and down while diving, i can only use vr to look up and down. while left and right can be done with the mouse (which I like).

Thank you.

**Comment by IWhoI** [comment]
I didn't include the option to look up and down with the mouse since weird stuff can happen with the camera when you can control the vertical with the mouse. If you are looking straight ahead with your headset and then use the mouse to look straight down at your feet and then you look down with your headset, the camera will rotate through the character body and be looking backwards and upside down. If you really still want it, there is another mod that does it https://www.nexusmods.com/subnautica/mods/1157

**Comment by RHuehne** [comment]
okay! thanks for explaining, makes sense!
